package exceptionHandling;

public class Main {

	public static void main(String[] args) {
		int a=2;
		int b=0;
		try {

			int c=a+b;
			 c=a-b;
			 c=a/b;
			 System.out.println(c);	
		}
		catch(ArithmeticException e) {
			System.out.println(e.getMessage()+" error occur");
		}
		System.out.println(a);
	}

}
